remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Vednarayan Iyer]
description: [Personal Webpage]

github:
  is_project_page: false
